-- IMFIT reference catalog seed. Idempotent and safe to rerun.

insert into public.muscle_categories
  (id, name, display_name, icon_name, sort_order)
values
  (1, 'CHEST', 'Chest', 'chest', 1),
  (2, 'BACK', 'Back', 'back', 2),
  (3, 'SHOULDERS', 'Shoulders', 'shoulders', 3),
  (4, 'BICEPS', 'Biceps', 'biceps', 4),
  (5, 'TRICEPS', 'Triceps', 'triceps', 5),
  (6, 'LEGS', 'Legs', 'legs', 6),
  (7, 'CORE', 'Core', 'core', 7),
  (8, 'CARDIO', 'Cardio', 'cardio', 8)
on conflict (id) do update set
  name = excluded.name,
  display_name = excluded.display_name,
  icon_name = excluded.icon_name,
  sort_order = excluded.sort_order;

select setval(
  pg_get_serial_sequence('public.muscle_categories', 'id'),
  greatest((select max(id) from public.muscle_categories), 1),
  true
);

insert into public.exercises
  (id, muscle_category_id, name, description, image_url, video_url,
   difficulty, equipment, is_active)
values
  ('ex_back_1', 2, 'Deadlift', 'Stand feet hip-width, grip barbell, lift by extending hips and knees.', null, null, 'ADVANCED', null, true),
  ('ex_back_10', 2, 'Straight-Arm Pulldown', 'Stand at cable machine, keep arms straight, push bar to thighs.', null, null, 'BEGINNER', null, true),
  ('ex_back_2', 2, 'Pull-Ups', 'Hang from bar with overhand grip, pull up until chin clears bar.', null, null, 'INTERMEDIATE', null, true),
  ('ex_back_3', 2, 'Barbell Row', 'Bend at hips, grip barbell, pull to lower chest.', null, null, 'INTERMEDIATE', null, true),
  ('ex_back_4', 2, 'Lat Pulldown', 'Sit at machine, pull bar down to upper chest.', null, null, 'BEGINNER', null, true),
  ('ex_back_5', 2, 'Seated Cable Row', 'Sit at cable machine, pull handle to lower chest.', null, null, 'BEGINNER', null, true),
  ('ex_back_6', 2, 'T-Bar Row', 'Straddle the bar, hinge at hips, pull weight toward chest.', null, null, 'INTERMEDIATE', null, true),
  ('ex_back_7', 2, 'Single-Arm Dumbbell Row', 'Knee on bench, pull dumbbell to hip with one arm.', null, null, 'BEGINNER', null, true),
  ('ex_back_8', 2, 'Back Extensions', 'Lock heels in pad, lower torso and raise using lower back.', null, null, 'BEGINNER', null, true),
  ('ex_back_9', 2, 'Chin-Ups', 'Hang from bar with underhand grip, pull up until chin clears bar.', null, null, 'INTERMEDIATE', null, true),
  ('ex_biceps_1', 4, 'Barbell Curl', 'Stand with barbell, curl up by flexing elbows.', null, null, 'BEGINNER', null, true),
  ('ex_biceps_10', 4, 'Spider Curl', 'Lie face down on incline bench, curl barbell up.', null, null, 'INTERMEDIATE', null, true),
  ('ex_biceps_2', 4, 'Dumbbell Curl', 'Alternating curls with dumbbells.', null, null, 'BEGINNER', null, true),
  ('ex_biceps_3', 4, 'Hammer Curl', 'Curl with neutral grip throughout.', null, null, 'BEGINNER', null, true),
  ('ex_biceps_4', 4, 'Preacher Curl', 'Rest arms on preacher bench, curl up.', null, null, 'INTERMEDIATE', null, true),
  ('ex_biceps_5', 4, 'Cable Curl', 'Stand facing cable, curl bar up.', null, null, 'BEGINNER', null, true),
  ('ex_biceps_6', 4, 'Concentration Curl', 'Sit on bench, rest elbow on inner thigh, curl dumbbell.', null, null, 'BEGINNER', null, true),
  ('ex_biceps_7', 4, 'Incline Dumbbell Curl', 'Sit on incline bench, let arms hang, curl dumbbells up.', null, null, 'INTERMEDIATE', null, true),
  ('ex_biceps_8', 4, 'Reverse Curl', 'Hold barbell with overhand grip, curl up targeting forearms.', null, null, 'BEGINNER', null, true),
  ('ex_biceps_9', 4, 'Zottman Curl', 'Curl up with palms up, rotate palms down, lower slowly.', null, null, 'INTERMEDIATE', null, true),
  ('ex_cardio_1', 8, 'Treadmill Running', 'Run on treadmill.', null, null, 'BEGINNER', null, true),
  ('ex_cardio_10', 8, 'Jumping Jacks', 'Jump spreading legs and clapping hands overhead.', null, null, 'BEGINNER', null, true),
  ('ex_cardio_2', 8, 'Stationary Bike', 'Cycle on stationary bike.', null, null, 'BEGINNER', null, true),
  ('ex_cardio_3', 8, 'Rowing Machine', 'Full body cardio with rowing.', null, null, 'INTERMEDIATE', null, true),
  ('ex_cardio_4', 8, 'Jump Rope', 'Skip rope continuously.', null, null, 'BEGINNER', null, true),
  ('ex_cardio_5', 8, 'Burpees', 'Full body exercise with jump.', null, null, 'INTERMEDIATE', null, true),
  ('ex_cardio_6', 8, 'Elliptical Trainer', 'Low impact cardio on elliptical machine.', null, null, 'BEGINNER', null, true),
  ('ex_cardio_7', 8, 'Stair Climber', 'Climb steps continuously on machine.', null, null, 'INTERMEDIATE', null, true),
  ('ex_cardio_8', 8, 'Box Jumps', 'Jump with two feet onto a box.', null, null, 'INTERMEDIATE', null, true),
  ('ex_cardio_9', 8, 'High Knees', 'Run in place lifting knees high.', null, null, 'BEGINNER', null, true),
  ('ex_chest_1', 1, 'Barbell Bench Press', 'Lie on flat bench, grip barbell wider than shoulders, lower to chest, press up.', null, null, 'INTERMEDIATE', null, true),
  ('ex_chest_10', 1, 'Incline Push-Ups', 'Perform push-ups with hands placed on an elevated surface.', null, null, 'BEGINNER', null, true),
  ('ex_chest_2', 1, 'Incline Dumbbell Press', 'Set bench to 30-45 degrees, press dumbbells up from shoulder level.', null, null, 'INTERMEDIATE', null, true),
  ('ex_chest_3', 1, 'Cable Flyes', 'Stand between cables, bring handles together in front of chest.', null, null, 'BEGINNER', null, true),
  ('ex_chest_4', 1, 'Push-Ups', 'Standard push-up, lower until chest nearly touches floor, push back up.', null, null, 'BEGINNER', null, true),
  ('ex_chest_5', 1, 'Dumbbell Flyes', 'Lie on bench, extend arms above chest, lower in arc motion to sides.', null, null, 'INTERMEDIATE', null, true),
  ('ex_chest_6', 1, 'Decline Bench Press', 'Lie on decline bench, press barbell up to target lower chest.', null, null, 'INTERMEDIATE', null, true),
  ('ex_chest_7', 1, 'Machine Chest Press', 'Sit in machine, push handles forward until arms are extended.', null, null, 'BEGINNER', null, true),
  ('ex_chest_8', 1, 'Pec Deck Machine', 'Sit with arms at 90 degrees, bring elbows together in front.', null, null, 'BEGINNER', null, true),
  ('ex_chest_9', 1, 'Dips (Chest Focus)', 'Lean forward on parallel bars, lower body and push up.', null, null, 'INTERMEDIATE', null, true),
  ('ex_core_1', 7, 'Plank', 'Hold push-up position on forearms.', null, null, 'BEGINNER', null, true),
  ('ex_core_10', 7, 'Hanging Knee Raise', 'Hang from bar, lift knees toward chest.', null, null, 'INTERMEDIATE', null, true),
  ('ex_core_2', 7, 'Crunches', 'Lie on back, curl shoulders toward hips.', null, null, 'BEGINNER', null, true),
  ('ex_core_3', 7, 'Russian Twist', 'Sit, lean back, rotate torso.', null, null, 'BEGINNER', null, true),
  ('ex_core_4', 7, 'Leg Raises', 'Lie on back, raise legs vertical.', null, null, 'INTERMEDIATE', null, true),
  ('ex_core_5', 7, 'Cable Woodchop', 'Pull cable diagonally across body.', null, null, 'INTERMEDIATE', null, true),
  ('ex_core_6', 7, 'Ab Wheel Rollout', 'Kneel, roll wheel forward extending body, roll back.', null, null, 'ADVANCED', null, true),
  ('ex_core_7', 7, 'Bicycle Crunches', 'Lie on back, touch elbow to opposite knee alternating.', null, null, 'BEGINNER', null, true),
  ('ex_core_8', 7, 'Mountain Climbers', 'Plank position, drive knees to chest rapidly.', null, null, 'BEGINNER', null, true),
  ('ex_core_9', 7, 'Side Plank', 'Hold body straight supported by one forearm on side.', null, null, 'INTERMEDIATE', null, true),
  ('ex_legs_1', 6, 'Barbell Squat', 'Bar on back, squat until thighs parallel.', null, null, 'INTERMEDIATE', null, true),
  ('ex_legs_10', 6, 'Glute Bridge', 'Lie on back, lift hips toward ceiling squeezing glutes.', null, null, 'BEGINNER', null, true),
  ('ex_legs_11', 6, 'Goblet Squat', 'Hold one dumbbell at chest height, squat down.', null, null, 'BEGINNER', null, true),
  ('ex_legs_2', 6, 'Leg Press', 'Push platform away at leg press machine.', null, null, 'BEGINNER', null, true),
  ('ex_legs_3', 6, 'Romanian Deadlift', 'Hinge at hips, lower weight along legs.', null, null, 'INTERMEDIATE', null, true),
  ('ex_legs_4', 6, 'Leg Curl', 'Lie face down, curl weight up.', null, null, 'BEGINNER', null, true),
  ('ex_legs_5', 6, 'Leg Extension', 'Sit in machine, extend legs.', null, null, 'BEGINNER', null, true),
  ('ex_legs_6', 6, 'Calf Raises', 'Raise heels as high as possible.', null, null, 'BEGINNER', null, true),
  ('ex_legs_7', 6, 'Lunges', 'Step forward, lower back knee.', null, null, 'BEGINNER', null, true),
  ('ex_legs_8', 6, 'Bulgarian Split Squat', 'One foot elevated behind, squat with front leg.', null, null, 'INTERMEDIATE', null, true),
  ('ex_legs_9', 6, 'Hack Squat', 'Use hack squat machine to squat at an angle.', null, null, 'INTERMEDIATE', null, true),
  ('ex_shoulders_1', 3, 'Overhead Press', 'Stand with barbell at shoulders, press overhead.', null, null, 'INTERMEDIATE', null, true),
  ('ex_shoulders_10', 3, 'Handstand Push-Ups', 'Invert body against wall, lower head to floor and press up.', null, null, 'ADVANCED', null, true),
  ('ex_shoulders_2', 3, 'Lateral Raises', 'Hold dumbbells at sides, raise laterally to shoulder height.', null, null, 'BEGINNER', null, true),
  ('ex_shoulders_3', 3, 'Front Raises', 'Hold dumbbells, raise one arm at a time to shoulder height.', null, null, 'BEGINNER', null, true),
  ('ex_shoulders_4', 3, 'Face Pulls', 'Pull rope toward face, separating hands.', null, null, 'BEGINNER', null, true),
  ('ex_shoulders_5', 3, 'Arnold Press', 'Start dumbbells in front, rotate and press overhead.', null, null, 'INTERMEDIATE', null, true),
  ('ex_shoulders_6', 3, 'Upright Row', 'Pull barbell or dumbbells vertically up toward chin.', null, null, 'INTERMEDIATE', null, true),
  ('ex_shoulders_7', 3, 'Seated Dumbbell Press', 'Sit on bench with back support, press dumbbells overhead.', null, null, 'BEGINNER', null, true),
  ('ex_shoulders_8', 3, 'Reverse Pec Deck', 'Sit facing machine, pull handles back to target rear delts.', null, null, 'BEGINNER', null, true),
  ('ex_shoulders_9', 3, 'Dumbbell Shrugs', 'Hold heavy dumbbells, shrug shoulders up toward ears.', null, null, 'BEGINNER', null, true),
  ('ex_triceps_1', 5, 'Tricep Pushdown', 'Push bar down at cable machine.', null, null, 'BEGINNER', null, true),
  ('ex_triceps_10', 5, 'Single-Arm Overhead Extension', 'One arm dumbbell extension performed overhead.', null, null, 'BEGINNER', null, true),
  ('ex_triceps_2', 5, 'Skull Crushers', 'Lie on bench, lower barbell toward forehead.', null, null, 'INTERMEDIATE', null, true),
  ('ex_triceps_3', 5, 'Overhead Tricep Extension', 'Hold dumbbell overhead, lower behind head.', null, null, 'BEGINNER', null, true),
  ('ex_triceps_4', 5, 'Close-Grip Bench Press', 'Bench press with narrow grip.', null, null, 'INTERMEDIATE', null, true),
  ('ex_triceps_5', 5, 'Tricep Dips', 'Support on parallel bars, lower and push up.', null, null, 'INTERMEDIATE', null, true),
  ('ex_triceps_6', 5, 'Diamond Push-Ups', 'Push-up with hands close together forming a diamond shape.', null, null, 'INTERMEDIATE', null, true),
  ('ex_triceps_7', 5, 'Tricep Kickbacks', 'Bend over, extend arm back keeping elbow high.', null, null, 'BEGINNER', null, true),
  ('ex_triceps_8', 5, 'Bench Dips', 'Hands on bench behind you, lower hips and press up.', null, null, 'BEGINNER', null, true),
  ('ex_triceps_9', 5, 'Rope Pushdown', 'Use rope attachment on cable, spread hands at bottom.', null, null, 'BEGINNER', null, true)
on conflict (id) do update set
  muscle_category_id = excluded.muscle_category_id,
  name = excluded.name,
  description = excluded.description,
  image_url = excluded.image_url,
  video_url = excluded.video_url,
  difficulty = excluded.difficulty,
  equipment = excluded.equipment,
  is_active = excluded.is_active;
