-- IMFIT schema baseline for environments whose original schema was created manually.
-- This migration is intentionally idempotent so it can be recorded on the current
-- project and can also bootstrap a fresh Supabase project.

set lock_timeout = '5s';
set statement_timeout = '30s';

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name varchar not null,
  email varchar not null,
  birth_date date,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.muscle_categories (
  id integer generated by default as identity primary key,
  name varchar not null unique,
  display_name varchar not null,
  icon_name varchar,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.exercises (
  id varchar primary key,
  muscle_category_id integer not null
    references public.muscle_categories(id) on delete restrict,
  name varchar not null unique,
  description text not null,
  image_url text,
  video_url text,
  difficulty varchar default 'INTERMEDIATE'
    check (difficulty in ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
  equipment varchar,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_templates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name varchar not null check (char_length(name) >= 2),
  description text,
  estimated_duration integer,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.template_exercises (
  id uuid primary key default gen_random_uuid(),
  template_id uuid not null
    references public.workout_templates(id) on delete cascade,
  exercise_id varchar not null
    references public.exercises(id) on delete restrict,
  order_index integer not null default 0 check (order_index >= 0),
  sets integer not null default 3 check (sets between 1 and 20),
  reps integer not null default 10 check (reps between 1 and 100),
  rest_seconds integer not null default 60 check (rest_seconds between 0 and 600),
  notes varchar,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  template_id uuid references public.workout_templates(id) on delete set null,
  template_name varchar not null,
  date date not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  total_volume numeric not null default 0 check (total_volume >= 0),
  total_sets integer not null default 0,
  total_reps integer not null default 0,
  notes text,
  rating integer check (rating is null or rating between 1 and 5),
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  updated_at timestamptz not null default now(),
  check (end_time > start_time)
);

create table if not exists public.exercise_logs (
  id uuid primary key default gen_random_uuid(),
  workout_log_id uuid not null
    references public.workout_logs(id) on delete cascade,
  exercise_id varchar not null
    references public.exercises(id) on delete restrict,
  exercise_name varchar not null,
  muscle_category varchar not null,
  order_index integer not null default 0 check (order_index >= 0),
  total_volume numeric not null default 0,
  created_at timestamptz not null default now(),
  total_sets integer not null default 0,
  total_reps integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.workout_sets (
  id uuid primary key default gen_random_uuid(),
  exercise_log_id uuid not null
    references public.exercise_logs(id) on delete cascade,
  set_number integer not null check (set_number >= 1),
  weight numeric not null default 0 check (weight between 0 and 1000),
  reps integer not null default 0 check (reps between 0 and 1000),
  is_completed boolean not null default false,
  is_warmup boolean not null default false,
  notes varchar,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  workout_log_id uuid references public.workout_logs(id) on delete cascade,
  exercise_id varchar
);

create table if not exists public.active_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  template_id uuid not null
    references public.workout_templates(id) on delete cascade,
  template_name varchar not null,
  start_time timestamptz not null default now(),
  current_exercise_index integer not null default 0,
  session_data jsonb not null default '{}'::jsonb,
  last_activity_at timestamptz not null default now(),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_template_exercises_order
  on public.template_exercises (template_id, order_index);
create unique index if not exists idx_workout_sets_number
  on public.workout_sets (exercise_log_id, set_number);
create unique index if not exists idx_templates_user_name
  on public.workout_templates (user_id, name) where is_deleted = false;
create index if not exists idx_templates_user
  on public.workout_templates (user_id);
create index if not exists idx_templates_user_active
  on public.workout_templates (user_id) where is_deleted = false;
create index if not exists idx_template_exercises_template
  on public.template_exercises (template_id);
create index if not exists idx_workout_logs_user
  on public.workout_logs (user_id);
create index if not exists idx_workout_logs_user_date
  on public.workout_logs (user_id, date desc);
create index if not exists idx_workout_logs_deleted_at
  on public.workout_logs (deleted_at);
create index if not exists idx_exercise_logs_workout
  on public.exercise_logs (workout_log_id);
create index if not exists idx_workout_sets_exercise_log
  on public.workout_sets (exercise_log_id);
create index if not exists idx_workout_sets_workout_log_id
  on public.workout_sets (workout_log_id);
create index if not exists idx_workout_sets_exercise_id
  on public.workout_sets (exercise_id);
create index if not exists idx_exercises_category
  on public.exercises (muscle_category_id);
create index if not exists idx_exercises_active
  on public.exercises (is_active) where is_active = true;
create index if not exists idx_profiles_email
  on public.profiles (email);

insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', false),
  ('exercises', 'exercises', false)
on conflict (id) do nothing;
